#!/usr/bin/env pwsh

# This script in intented for install on Linux environments
# Requires powershell installed
# Install with:
#
# Powershell:
# (Invoke-WebRequest -Uri "https://raw.githubusercontent.com/radekp31/nixos/refs/heads/main/modules/home/shells/powershell/portable.ps1").Content | pwsh -NoProfile -Command -
#
#OR
#
#Bash:
#curl -fsSL "https://raw.githubusercontent.com/radekp31/nixos/refs/heads/main/modules/home/shells/powershell/portable.ps1" | pwsh -NoProfile -Command -


if (Test-Path $PROFILE) {
    Copy-Item $PROFILE "$PROFILE.manual-backup"
}

[CmdletBinding()]
param(
    [string]$OhMyPoshTheme = 'powerlevel10k_lean'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Get-LinuxArchitecture {
    $architecture = [Runtime.InteropServices.RuntimeInformation]::OSArchitecture

    switch ($architecture) {
        'X64'   { return 'amd64' }
        'Arm64' { return 'arm64' }
        default { throw "Unsupported architecture: $architecture" }
    }
}

function Get-LatestGitHubRelease {
    param(
        [Parameter(Mandatory)]
        [string]$Repository
    )

    Invoke-RestMethod `
        -Uri "https://api.github.com/repos/$Repository/releases/latest" `
        -Headers @{ Accept = 'application/vnd.github+json'; 'User-Agent' = 'Azure-Cloud-Shell-Setup' }
}

function Save-GitHubReleaseAsset {
    param(
        [Parameter(Mandatory)]
        [object]$Asset,

        [Parameter(Mandatory)]
        [string]$Destination
    )

    Invoke-WebRequest `
        -Uri $Asset.browser_download_url `
        -OutFile $Destination `
        -Headers @{ Accept = 'application/octet-stream'; 'User-Agent' = 'Azure-Cloud-Shell-Setup' }

    if ($Asset.PSObject.Properties.Name -contains 'digest' -and $Asset.digest -match '^sha256:(?<Hash>[0-9a-fA-F]{64})$') {
        $actualHash = (Get-FileHash -LiteralPath $Destination -Algorithm SHA256).Hash
        if ($actualHash -ne $Matches.Hash) {
            Remove-Item -LiteralPath $Destination -Force -ErrorAction SilentlyContinue
            throw "Checksum verification failed for $($Asset.name)."
        }
    }
}

if (-not [Runtime.InteropServices.RuntimeInformation]::IsOSPlatform([Runtime.InteropServices.OSPlatform]::Linux)) {
    throw 'This installer targets the Linux-based Azure Cloud Shell.'
}

$architecture = Get-LinuxArchitecture
$binDirectory = Join-Path $HOME '.local/bin'
New-Item -ItemType Directory -Path $binDirectory -Force | Out-Null
$env:PATH = "${binDirectory}:" + $env:PATH

Write-Host 'Installing Oh My Posh...'
$ohMyPoshRelease = Get-LatestGitHubRelease -Repository 'JanDeDobbeleer/oh-my-posh'
$ohMyPoshAssetName = "posh-linux-$architecture"
$ohMyPoshAsset = $ohMyPoshRelease.assets |
    Where-Object name -EQ $ohMyPoshAssetName |
    Select-Object -First 1

if ($null -eq $ohMyPoshAsset) {
    throw "Release asset not found: $ohMyPoshAssetName"
}

$ohMyPoshPath = Join-Path $binDirectory 'oh-my-posh'
Save-GitHubReleaseAsset -Asset $ohMyPoshAsset -Destination $ohMyPoshPath
& chmod +x $ohMyPoshPath
if ($LASTEXITCODE -ne 0) {
    throw 'Failed to make Oh My Posh executable.'
}

Write-Host 'Installing fzf...'
$fzfRelease = Get-LatestGitHubRelease -Repository 'junegunn/fzf'
$fzfVersion = $fzfRelease.tag_name.TrimStart('v')
$fzfAssetName = "fzf-$fzfVersion-linux_$architecture.tar.gz"
$fzfAsset = $fzfRelease.assets |
    Where-Object name -EQ $fzfAssetName |
    Select-Object -First 1

if ($null -eq $fzfAsset) {
    throw "Release asset not found: $fzfAssetName"
}

$temporaryDirectory = Join-Path ([IO.Path]::GetTempPath()) "cloudshell-prompt-$([guid]::NewGuid())"
New-Item -ItemType Directory -Path $temporaryDirectory -Force | Out-Null

try {
    $fzfArchive = Join-Path $temporaryDirectory $fzfAssetName
    Save-GitHubReleaseAsset -Asset $fzfAsset -Destination $fzfArchive

    & tar -xzf $fzfArchive -C $binDirectory fzf
    if ($LASTEXITCODE -ne 0) {
        throw 'Failed to extract fzf.'
    }

    & chmod +x (Join-Path $binDirectory 'fzf')
    if ($LASTEXITCODE -ne 0) {
        throw 'Failed to make fzf executable.'
    }
}
finally {
    Remove-Item -LiteralPath $temporaryDirectory -Recurse -Force -ErrorAction SilentlyContinue
}

Write-Host 'Installing PSFzf...'
Install-Module `
    -Name PSFzf `
    -Scope CurrentUser `
    -Repository PSGallery `
    -Force `
    -AllowClobber `
    -AcceptLicense

$profilePath = $PROFILE.CurrentUserCurrentHost
$profileDirectory = Split-Path -Parent $profilePath
New-Item -ItemType Directory -Path $profileDirectory -Force | Out-Null

if (Test-Path -LiteralPath $profilePath) {
    $backupPath = "$profilePath.backup-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
    Copy-Item -LiteralPath $profilePath -Destination $backupPath
    Write-Host "Existing profile backed up to: $backupPath"
}

$escapedTheme = $OhMyPoshTheme.Replace("'", "''")
$profileContent = @"
# Generated by install-azure-cloudshell-prompt.ps1.
# Re-running the installer backs up and replaces this profile.

`$env:PATH = "`$HOME/.local/bin:" + `$env:PATH

# Cloud Shell normally loads PSReadLine before this profile.
if (-not (Get-Command Get-PSReadLineKeyHandler -ErrorAction SilentlyContinue)) {
    Import-Module PSReadLine -ErrorAction Stop
}

if (-not (Get-Command oh-my-posh -ErrorAction SilentlyContinue)) {
    throw 'oh-my-posh is not available on PATH.'
}

oh-my-posh init pwsh --eval --config '$escapedTheme' | Invoke-Expression

Import-Module PSFzf -ErrorAction Stop

`$psFzfOptions = @{
    PSReadlineChordProvider       = 'Ctrl+t'
    PSReadlineChordReverseHistory = 'Ctrl+r'
    TabCompletionPreviewWindow   = 'hidden|down|right|hidden'
}
Set-PsFzfOption @psFzfOptions

function Invoke-HybridTabCompletion {
    `$line = `$null
    `$cursor = 0

    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState(
        [ref]`$line,
        [ref]`$cursor
    )

    `$textBeforeCursor = `$line.Substring(0, `$cursor)

    # Preserve native semantic completion outside command position.
    if (`$textBeforeCursor -notmatch '^\s*\S*`$') {
        [Microsoft.PowerShell.PSConsoleReadLine]::Complete()
        return
    }

    `$completion = [System.Management.Automation.CommandCompletion]::CompleteInput(
        `$line,
        `$cursor,
        `$null
    )

    `$matches = @(`$completion.CompletionMatches)

    if (`$matches.Count -eq 0) {
        [Microsoft.PowerShell.PSConsoleReadLine]::Ding()
        return
    }

    if (`$matches.Count -eq 1) {
        [Microsoft.PowerShell.PSConsoleReadLine]::Replace(
            `$completion.ReplacementIndex,
            `$completion.ReplacementLength,
            `$matches[0].CompletionText
        )
        return
    }

    `$selectedText = `$matches |
        ForEach-Object { `$_.ListItemText } |
        Invoke-Fzf -Prompt 'Command> '

    if ([string]::IsNullOrWhiteSpace(`$selectedText)) {
        return
    }

    `$selectedMatch = `$matches |
        Where-Object { `$_.ListItemText -eq `$selectedText } |
        Select-Object -First 1

    if (`$null -eq `$selectedMatch) {
        return
    }

    [Microsoft.PowerShell.PSConsoleReadLine]::Replace(
        `$completion.ReplacementIndex,
        `$completion.ReplacementLength,
        `$selectedMatch.CompletionText
    )
}

Set-PSReadLineKeyHandler -Key Tab -ScriptBlock { Invoke-HybridTabCompletion }
Set-PSReadLineKeyHandler -Key 'Ctrl+Spacebar' -ScriptBlock { Invoke-FzfTabCompletion }
"@

Set-Content -LiteralPath $profilePath -Value $profileContent -Encoding utf8NoBOM

Write-Host 'Verifying installation...'
$requiredCommands = @('oh-my-posh', 'fzf')
foreach ($commandName in $requiredCommands) {
    if (-not (Get-Command $commandName -ErrorAction SilentlyContinue)) {
        throw "Verification failed: $commandName is unavailable."
    }
}

Import-Module PSFzf -Force -ErrorAction Stop
$requiredModuleCommands = @('Invoke-Fzf', 'Invoke-FzfTabCompletion', 'Set-PsFzfOption')
foreach ($commandName in $requiredModuleCommands) {
    if (-not (Get-Command $commandName -ErrorAction SilentlyContinue)) {
        throw "Verification failed: $commandName is unavailable."
    }
}

Write-Host ''
Write-Host 'Azure Cloud Shell prompt setup completed successfully.' -ForegroundColor Green
Write-Host "Oh My Posh: $(& $ohMyPoshPath version)"
Write-Host "fzf: $(& (Join-Path $binDirectory 'fzf') --version)"
Write-Host "Profile: $profilePath"
Write-Host ''
Write-Host 'Activate it in the current shell with:' -ForegroundColor Cyan
Write-Host '. $PROFILE'
Write-Host ''
Write-Host 'Key bindings:' -ForegroundColor Cyan
Write-Host '  Tab          Hybrid command/native completion'
Write-Host '  Ctrl+Space   PSFzf token completion'
Write-Host '  Ctrl+R       Fuzzy history search'
Write-Host '  Ctrl+T       Fuzzy provider/file selection'
