keys:
  - &hosts_nixos-desktop age1hrntn7v7psk7lpdx5vna99fun480le75lk66rmqmqk744w3plqjqnrcj0x
  - &hosts_contabovps1 age1fr9lpceue3swhp8tkqzptud6s5f2ft509grc5r52h2u6zufp7flq9fdlma
  #- &hosts_nixos-desktop >- ${SOPS_AGE_KEY_FILE:-/var/lib/sops-nix/keys.txt}
  - &hosts_dt-laptop age1ts3n6rghxr38h2cmu0v5y6emlyf98teeg0rxva6d2tha5pm7yg6s5uwhtw
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *hosts_nixos-desktop
          - *hosts_contabovps1
          - *hosts_dt-laptop
