# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  pkgs,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/afdb1618-6f2a-469f-83cc-4f4f37b3a780";
    fsType = "btrfs";
    options = ["subvol=@" "compress=zstd" "noatime"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/afdb1618-6f2a-469f-83cc-4f4f37b3a780";
    fsType = "btrfs";
    options = ["subvol=@home" "compress=zstd" "noatime"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/afdb1618-6f2a-469f-83cc-4f4f37b3a780";
    fsType = "btrfs";
    options = ["subvol=@nix" "compress=zstd" "noatime"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/afdb1618-6f2a-469f-83cc-4f4f37b3a780";
    fsType = "btrfs";
    options = ["subvol=@log" "compress=zstd" "noatime"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/91EC-ACD4";
    fsType = "vfat";
  };

  fileSystems."/media/WDRED" = {
    device = "/dev/disk/by-uuid/C6541CA0541C9571";
    fsType = "ntfs";
    options = ["rw" "nofail"];
  };

  fileSystems."/media/A400" = {
    device = "/dev/disk/by-uuid/2b232c2c-3198-432d-bcbe-9d6056700d12";
    fsType = "xfs";
    #options = ["rw" "nofail"];
    options = ["rw" "nofail" "defaults" "noatime"];
  };

  fileSystems."/mnt/btr_pool" = {
    device = "/dev/disk/by-uuid/afdb1618-6f2a-469f-83cc-4f4f37b3a780";
    fsType = "btrfs";
    options = ["subvolid=5"]; # This mounts the actual top-level of the drive
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  services.btrfs = {
    autoScrub = {
      enable = true;
    };
  };

  environment.systemPackages = with pkgs; [btrbk];

  systemd.tmpfiles.rules = [
    "d /mnt/btr_pool/.snapshots 0700 root root -"
    "d /mnt/btr_pool/.snapshots/@ 0700 root root -"
    "d /mnt/btr_pool/.snapshots/@home 0700 root root -"
  ];

  services.btrbk.instances."local" = {
    onCalendar = "hourly";
    settings = {
      snapshot_preserve_min = "2d";
      snapshot_preserve = "24h 14d 12w";

      volume."/mnt/btr_pool" = {
        # This creates snapshots in /mnt/btr_pool/.snapshots/
        snapshot_dir = ".snapshots";

        subvolume."@home" = {}; # Inherits hourly

        subvolume."@" = {
          # Set to manual/ondemand
          snapshot_create = "ondemand";
        };
      };
    };
  };

  systemd.services.btrbk-daily-root = {
    description = "Trigger daily btrbk snapshots for root";

    # Ensure the btrbk service is available
    after = ["local-fs.target"];

    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${pkgs.btrbk}/bin/btrbk -c /etc/btrbk/local.conf run @";
      User = "root";
    };
  };

  systemd.timers.btrbk-daily-root = {
    description = "Timer for daily root snapshots";
    wantedBy = ["timers.target"];
    timerConfig = {
      OnCalendar = "daily";
      Persistent = true; # Run immediately if the computer was off at midnight
    };
  };
}
